services:
  postgres:
    image: docker.io/library/postgres:18.3
    container_name: sphare-postgres-18
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: <keycloak-db-password>
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
  postgres-test:
    image: docker.io/library/postgres:18.3
    container_name: sphare-postgres-test
    environment:
      POSTGRES_USER: <test-db-user>
      POSTGRES_PASSWORD: <test-db-password>
    volumes:
      - postgres_test_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.0
    container_name: sphare-keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=<keycloak-admin-username>
      - KC_BOOTSTRAP_ADMIN_PASSWORD=<keycloak-admin-password>
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=<keycloak-db-password>
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8443:8443"
    command:
      - start-dev
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
    name: sphare-pg-data
  postgres_test_data:
    driver: local
    name: sphare-pg-data-test